### ISSUE TITLE
Submit List Button

### ISSUE THREAD

**Issue by federicoast** [kleros/gtcr#101]
The SUBMIT LIST button is a very visible button in the interface.

Do we want to keep it there?

To me it maybe makes more sense to have the CREATE LIST button there (and put the SUBMIT BUTTON in the header).

All of the lists that will be shown in the interface will start the process by CREATE LIST.

What do you think?

![FireShot Capture 1053 - Kleros · Curate_ - https___curate kleros io_tcr_0x79](https://user-images.githubusercontent.com/16290963/83793005-47d75b80-a672-11ea-9ad8-b443787c5b90.jpg)

**Comment by mtsalenc** [comment]
This is a button common to all lists, the user might find it weird that some lists have it and some won't so I think we should keep it there.

**Comment by mtsalenc** [comment]
There was an error in the commit message that closed this issue.

**Comment by mtsalenc** [comment]
Closing this since it doesn't seem to be contentious. If someone disagrees post below and reopen.
