### ISSUE TITLE
Text changes in TCR browser badges

### ISSUE THREAD

**Issue by federicoast** [kleros/gtcr#107]
TCR Browser enabled badges ---> List Browser Badges
Submit TCR ---> Submit List
A TCR of TCRs related to TCR Browser ---> ??? NOT SURE WHAT TO WRITE HERE. MAYBE I'D JUST REMOVE THIS.

![FireShot Capture 1062 - Kleros · Curate_ - https___curate kleros io_tcr_0xf5](https://user-images.githubusercontent.com/16290963/84043628-ecacae00-a97c-11ea-880f-dbc0578caff3.jpg)

**Comment by mtsalenc** [comment]
The list description is not optional so we can't leave it blank in the list metadata. 
I _could_ manually hide it but I think it will confuse users.


Not a UI issue so no commit closing this issue, meta evidence update on tx:
https://kovan.etherscan.io/tx/0x0b0dded2c68fae2221244a2b5e7ded3b9dbc58e6504f36b87e15456575fc4134

**Comment by mtsalenc** [comment]
UI after update

![Screenshot from 2020-06-08 12-39-50](https://user-images.githubusercontent.com/9872474/84051232-33060b00-a985-11ea-8b19-e8c50687b666.png)
