### ISSUE TITLE
A list of lists

### ISSUE THREAD

**Issue by federicoast** [kleros/gtcr#108]
A List of lists ---> A list of lists created by users.

![FireShot Capture 1063 - Kleros · Curate_ - https___curate kleros io_tcr_0x79](https://user-images.githubusercontent.com/16290963/84045229-ee777100-a97e-11ea-9229-378caea5017c.jpg)

**Comment by mtsalenc** [comment]
Since this is not a UI issue (just the description picked when deploying this list) there is no commit fixing this. Below is the tx updating the meta evidence.

https://kovan.etherscan.io/tx/0x7a7230dd565c2d3bd27c19caf507caa153c05c92987920d4a0d3d7042e2b5a39
