### ISSUE TITLE
Words change in the home page

### ISSUE THREAD

**Issue by federicoast** [kleros/gtcr#114]
Curated Lists ---> The Registry
A curated list of curated lists submitted by users ---> A searchable registry of all lists submitted by users.

![FireShot Capture 1065 - Kleros · Curate - https___curate kleros io_factory](https://user-images.githubusercontent.com/16290963/84153857-c2bac080-aa3c-11ea-8a80-b3998d75b7f3.jpg)

**Comment by mtsalenc** [comment]
Updated in https://kovan.etherscan.io/tx/0x9636e41c2781562a4e659814d5b212305be7b7d7098de58108f7b53141dee99d
