### ISSUE TITLE
Incorrect Removal Challenge Compensation

### ISSUE THREAD

**Issue by federicoast** [kleros/gtcr#118]
@whwgeorge can you please write the text for this hover explainer?

<img width="627" alt="incorrect removal challenge compensation" src="https://user-images.githubusercontent.com/16290963/84161473-b38c4080-aa45-11ea-922d-33455a8d2b6b.png">

**Comment by whwgeorge** [comment]
This amount, which is included in the deposits that challengers to removal requests must make, is given to the removal requestor in the event that a challenged removal request is ultimately ruled to be correct. If Incorrect Removal Challenge Compensation is too high, users will be disincentivized from challenging removal requests and correct entries may be removed from the list unchallenged. If Incorrect Removal Challenge Compensation is too low, users may not be adequately incentivized to submit removal requests, and incorrect entries may remain on the list longer than they should.
