### ISSUE TITLE
Stake Multipliers

### ISSUE THREAD

**Issue by federicoast** [kleros/gtcr#120]
@whwgeorge these already have the little explainers, but I think they could be made more accurate. Please check them.

![FireShot Capture 1068 - Kleros · Curate - https___curate kleros io_factory](https://user-images.githubusercontent.com/16290963/84161956-3ad9b400-aa46-11ea-853e-2a0951b271db.jpg)

**Comment by whwgeorge** [comment]
The tooltips on the three stake multipliers seem reasonable to me. 

If we want to add some text about the tradeoffs you should be thinking about when setting these, it might make the most sense to put it in the text that is currently: 
"To appeal, in addition to paying enough fees to cover the payment to the jurors in case the appeal is lost, parties must also pay an additional stake. The stake of the side that ultimately loses the dispute is used as the reward given to the appeal fee contributors that funded the side that ultimately wins the dispute. This amount is calculated proportionally to the total juror fees required for appeal using the multipliers below, given in basis points. For example, a multiplier of 1000 will result in the stake being 10% of the total juror fees."

Maybe:
"To appeal, in addition to paying enough fees to cover the payment to the jurors in case the appeal is lost, parties must also pay an additional stake. The stake of the side that ultimately loses the dispute is used as the reward given to the appeal fee contributors that funded the side that ultimately wins the dispute. 

This amount is calculated proportionally to the total juror fees required for appeal using the multipliers below, given in basis points. For example, a multiplier of 1000 will result in the stake being 10% of the total juror fees.

If you choose very large stake multipliers, the expected returns of crowdfunders will improve, but appeal costs may become so large as to be a barrier. If you choose very small stake multipliers, total appeal costs are reduced, but crowdfunders may not be sufficiently incentivized to participate. Different multipliers can be chosen for the sides that won and lost the previous appeal round. The more one of these multipliers is larger than the other, the more the side with the smaller multiplier is favoured. "

**Comment by mtsalenc** [comment]
Due to #111, I've made a small change:

"
...

This amount is calculated proportionally to the total juror fees required for appeal using the multipliers below, given in percentage. For example, a multiplier of 10% will result in the stake being 10% of the total juror fees.

...
"
