### ISSUE TITLE
Notifications Bug 

### ISSUE THREAD

**Issue by zambian** [kleros/gtcr#133]
![Screenshot 2020-06-11 at 15 15 54](https://user-images.githubusercontent.com/36391096/84392453-b0868100-abfa-11ea-941d-f5abcb2e52f1.png)

Failed to save settings for notifications.

**Comment by mtsalenc** [comment]
Fixed on https://github.com/kleros/gtcr-notifications/commit/f00fff2184f1a03bd137fb402a93fc62f3fb16bc
