### ISSUE TITLE
Items Variable

### ISSUE THREAD

**Issue by federicoast** [kleros/gtcr#137]
I think the idea of letting users put the name of the item of the list here is good. But I fear that because of the subtleties of language, it will end up creating lots of interfaces with grammar mistakes (which would make them look unprofessional).

I'm thinking that maybe we should just hard code "item" and "items" where applicable, as this will be valid in every case.

But I'm not sure about this. We can discuss.

![FireShot Capture 1087 - Kleros · Curate - https___curate kleros io_factory](https://user-images.githubusercontent.com/16290963/84409092-57f7b980-abe3-11ea-98ac-fffbed57fcf9.jpg)

**Comment by mtsalenc** [comment]
So, "item" and "items" has been set as the default values for the factory. The user can change it if they want.
