### ISSUE TITLE
Fix some "No new windows" overshoot

### ISSUE THREAD

**Issue by clesaege** [kleros/gtcr#147]
It looks like all the new windows of the dapp were removed even when they are not classic link.
In particular:
- Left click on "view listing policies" starts a download but also links to a blank page 
![image](https://user-images.githubusercontent.com/8873352/87182204-31f13200-c2d3-11ea-90eb-e5b8dc0f4d47.png)
(here it's not a link to another page, but a download "action" button), so it shouldn't open a new page.
- Pop under about transactions are not open in a new page which can lead to losing the deployment flow (here they are not classic links but some sort of button and users would obviously want to stay on the page, so it's not a dark pattern).

**Comment by mtsalenc** [comment]
Links in evidence display interface should open in a new window.
