### ISSUE TITLE
Gas error when trying to submit an item

### ISSUE THREAD

**Issue by clesaege** [kleros/gtcr#149]
![image](https://user-images.githubusercontent.com/8873352/87236328-72d26f00-c3d7-11ea-8d9f-dfe450640d33.png)

**Comment by mtsalenc** [comment]
Can you please retry or give me the input data?

**Comment by clesaege** [comment]
Now I don't manage to reproduce. It's really with a long input.

**Comment by mtsalenc** [comment]
Fixed on commit d6e926.
