### ISSUE TITLE
GTCR not loading on chrome

### ISSUE THREAD

**Issue by clesaege** [kleros/gtcr#150]
![image](https://user-images.githubusercontent.com/8873352/87236362-115ed000-c3d8-11ea-8812-9bf3ef03d978.png)

**Comment by mtsalenc** [comment]
This TCR (0x79d0Ffb6109B45D539cC3E291088C11D34ffFFF9) is a TCR deployed on kovan and you wallet is connected to mainnet. Switch to kovan and it'll load.
