### ISSUE TITLE
Kleros Curate etherescabn footer link

### ISSUE THREAD

**Issue by jragosa** [kleros/gtcr#166]
Kleros Curate etherscan footer link links to Kleros Liquid not to Curate contracts
![image](https://user-images.githubusercontent.com/34345327/116900637-3e1af700-ac39-11eb-966f-143c99e3f0bc.png)

**Comment by gratestas** [comment]
should it be a dynamic link based on the network? @greenlucid @gmkung

**Comment by gmkung** [comment]
I never realised that link is clickable. I actually think it'd be fine if it didn't link to anything as I thought it looked just like a footer.
If we want to add a link to Etherscan for the contract, then it's more logical to add it next to the TCR's title, with a little arrow icon or something IMO. And yes that link should be chain specific (e.g. blockscout for xDai, Etherscan for ETH ...) I guess.
![image](https://user-images.githubusercontent.com/17244594/196951584-a708baf5-6570-4d3e-a56d-143fd572a32f.png)

**Comment by gratestas** [comment]
Good point. I will apply your suggestion. However, the footer component is part of the [kleros/react-component](https://www.npmjs.com/package/@kleros/components) package and will use the default explorer link anyway. So I will replace it with a normal text tag.

**Comment by gratestas** [comment]
linked to #167
