### ISSUE TITLE
Gnosis Chain (xDai) Block Explorer

### ISSUE THREAD

**Issue by shotaronowhere** [kleros/gtcr#200]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/10378902/150768200-be4670e3-e346-4aca-b569-6c5294ad210b.png">

Hyperlinks for Curate on xDai point towards xdai.etherscan/address/0x...., instead of blockscout.com/xdai/mainnet/address/0x...

Blockscout is the [official](https://www.xdaichain.com/for-developers/developer-resources) blockchain explorer

**Comment by salgozino** [comment]
This seems to have been corrected in the MR #202 

For the case of NFT curation list, the link should point to the chain where the NFT was minted, insted of the gnosis explorer. 
See the case of https://curate.kleros.io/tcr/0xD5994f15BE9987104D9821AA99d1C97227c7C08c/0x6b6eb4dc688cae500e6941973f3168b4b19b6772b881e03790175ed5fe6d1ae4 where the ChainID it's 1 (mainnet) but the link of the address points to blockscout.

**Comment by greenlucid** [comment]
Yup, this is solved already
As for the second request, @salgozino I don't think that's possible as the NFT list was created. Curate cannot be that smart
I could create a "rich address" datatype that encodes an address + chainId for those cases. something like `0x12341234134....c0fec0fe2452:100`
That would require creating a new NFT list but it could be worth it
