### ISSUE TITLE
Intermittent connection to Curate (xDAI)

### ISSUE THREAD

**Issue by NingF23** [kleros/gtcr#220]
![image](https://user-images.githubusercontent.com/83063111/162945982-a963939f-5a5e-4071-b092-01af18275de5.png)
![image](https://user-images.githubusercontent.com/83063111/162946199-2f74ca84-f228-4d9f-88c6-7ab6b9bf3e08.png)
![image](https://user-images.githubusercontent.com/83063111/162946414-a5c50f67-a844-46e8-90ed-42c4aabed494.png)

_Access to fetch at 'https://gtcr-notifications.kleros.io/100/api/notifications/' from origin 'https://curate.kleros.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

**Comment by jaybuidl** [comment]
This RPC error does not seem relevant anymore, closing. The CORS error is #219
