### ISSUE TITLE
Curate Kovan Parameters bugged

### ISSUE THREAD

**Issue by juansamitier** [kleros/gtcr#223]
When creating a list for Curate at Kovan Testnet, the "Twitter" and "File" features arent working properly.
The Twitter feature is not matching existing Twitter Accounts while the "File" format is returning the option of writing text instead of uploading a file.

**Comment by clesaege** [comment]
See

https://curate.kleros.io/tcr/0x86452aBF866367CcB563c30756a0a28e0DA8CbCe?chainId=42

On Kovan

**Comment by juansamitier** [comment]
I also submit a "Crypto Library" list with 3 items, whose challenge period
ends in 4 days.
And I think I will have to delete or challenge the domain service and
submit it again with other parameters due to the fact that if I insert a
link on a "text format" parameter ,the Curate platform itself indicates
there's a mistake (i prove it by creating a list  without making the public
submission)
Juan

**Comment by greenlucid** [comment]
This was just fixed

**Comment by juansamitier** [comment]
> This was just fixed

Hello, thanks!
The Twitter Feature is working perfectly.

The problem is the "file"  parameter is not .
I tried to submit the link of an image (so it's not necessary you need to change it ) but although it allows me to submit the item,it returns an error.

You can check it out here:
https://curate.kleros.io/tcr/42/0x86452aBF866367CcB563c30756a0a28e0DA8CbCe/0x5932a475e8dd02255b1def417fc594b3a37199350e68d696a30ecf31f241a6a5

**Comment by greenlucid** [comment]
That's because the field is of type "address" (160 bit EVM address) but you should have used a field "link" instead when creating the list

**Comment by juansamitier** [comment]
Mmm yes, that's strange.

I am pretty sure that when creating the list I use and re-check to be using the "File" parameter.
I don't understand if at some point when submitting the transaction, it was the parameter was restored to "address".

I think the best option might be :
-Try removing the list 
-Upload the same list just changing the format of the  logo parameter

What do you think?

**Comment by greenlucid** [comment]
Yeah, you can do that.
You could also modify the list "metaEvidence" that sets things like the policy and the fields it contains, but it's harder
