### ISSUE TITLE
Support for the arbitrator v2

### ISSUE THREAD

**Issue by jaybuidl** [kleros/gtcr#256]
Dependencies:
- #254 
- https://github.com/kleros/gtcr-injected-uis/issues/6
- https://github.com/kleros/gtcr-subgraph/issues/16
- https://github.com/kleros/tcr/issues/62

It's going to live in a separate v2 branch in the foreseeable future.

**Comment by jaybuidl** [comment]
>I don't need to support both kleros v1 and v2.

Yup, v2 only in this branch.

>Stop checking for appeals, remove the appeal logic altogether.

We don't demo the appeals right now. But appeals can be requested on the DisputeKit. Which one? We can ask KlerosCore: which disputeKit for this disputeID and this round.

```typescript
fundAppeal = async (disputeID, choice) => {
   const round = await KlerosCore.getNumberOfRounds(disputeID)
   (,,,,, disputeKitID) = await KlerosCore.getRoundInfo(disputeID, round)
   const disputeKit = await KlerosCore.disputeKitNodes(disputeKitID)
   disputeKit.fundAppeal(disputeID, choice)
}
```
(not tested)

> disputeStatus

Not sure how it is used in Curate. If needed for display purposes or some logic, you could dl

```typescript
const dispute = await KlerosCore.disputes(arbitratorDisputeID)
switch(dispute.period) { 
   case KlerosCore.appeal: { 
      // do DisputeStatus.Appealable stuffs here
      break; 
   } 
   case KlerosCore.execution: { 
      // do DisputeStatus.Solved stuffs here
      break; 
   } 
   default: { 
      // do DisputeStatus.Waiting stuffs here
      break; 
   } 
}
```

**Comment by greenlucid** [comment]
https://github.com/kleros/gtcr/pull/258

Will test if it works as intended later when an arbitrator frontend works to try it out.
