### ISSUE TITLE
Using WalletConnect login with Metamask Errors

### ISSUE THREAD

**Issue by ferittuncer** [kleros/gtcr#31]
I got a perma spinner with "awaiting authorization" toast message and qr-code modal.

**Comment by ferittuncer** [comment]
Hmm, now it worked, perhaps this was fixed recently?

**Comment by mtsalenc** [comment]
I will leave this open for further investigation.

**Comment by mtsalenc** [comment]
I cannot reproduce this. Reopen if it happens again.
