### ISSUE TITLE
Unable to set up notifications (using hardware wallet)

### ISSUE THREAD

**Issue by PresenceNumerique** [kleros/gtcr#32]
When trying to set up notifications, my hardware wallet is not triggered and i can't sign.
![image](https://user-images.githubusercontent.com/46331204/73774514-65f48400-4784-11ea-8e7f-8f0f48e9c49c.png)
Thus resulting in this error :
![image](https://user-images.githubusercontent.com/46331204/73774584-858bac80-4784-11ea-993d-9ee3d7bc625e.png)

I am using a ledger nano x with Brave.

**Comment by mtsalenc** [comment]
The commit message that closed this was incorrect. It closed issue #34 instead.

**Comment by clesaege** [comment]
So I tried with a ledger and got the same issue. Signing messages like in the court works. But here it seems you are using some advanced message functionality with parameters. I guess that is what is causing the issues.

**Comment by mtsalenc** [comment]
Unfortunately this is related to ledger itself and it seems that it won't be fixed soon:

https://www.reddit.com/r/ledgerwallet/comments/gcdx1f/any_hope_for_eip712_support/
https://github.com/MetaMask/metamask-extension/pull/5050#issuecomment-430713608

In the meantime we'll have to revert to using legacy signing.
