### ISSUE TITLE
TCR factory final deployment step UI

### ISSUE THREAD

**Issue by PresenceNumerique** [kleros/gtcr#34]
After having deployed a TCR, the UI seems to be stuck on this screen:

![image](https://user-images.githubusercontent.com/46331204/74595438-97e9ce00-5041-11ea-83fe-57c5453632ba.png)
1- As a user I expect the step 4 to be ticked and not to be able to deploy the same TCR right away.
2- When I connect at a later time I am still facing this same screen but i would expect a fresh screen with the history of what I already deployed.
3- Previous deployments list should also be in a human readable format if possible: if a user has several TCR deployed, it is a pain to know which transaction is related to which TCR and enabled TCR badges.
See after only 2 deployments:

![image](https://user-images.githubusercontent.com/46331204/74595740-80acdf80-5045-11ea-9255-b1d1c92f34ea.png)

**Comment by mtsalenc** [comment]
It should be gentler now. Thanks for the suggestions!
![Screenshot from 2020-05-22 16-25-02](https://user-images.githubusercontent.com/9872474/82702785-1198e580-9c49-11ea-95b0-1f7029ab9ab4.png)

**Comment by PresenceNumerique** [comment]
Excellent, great work!
