### ISSUE TITLE
Timestamping every entry of item details

### ISSUE THREAD

**Issue by PresenceNumerique** [kleros/gtcr#35]
A nice enhancement would have to get a timestamp for each historic detail of items:

![image](https://user-images.githubusercontent.com/46331204/74678936-b45e4580-51bc-11ea-9293-4735529c2a2b.png)
It would make sense to know when each entry has occurred:
"Item Submitted", "Item rejected", etc...

**Comment by mtsalenc** [comment]
You got it.

**Comment by PresenceNumerique** [comment]
Nice!
Thank you.
