### ISSUE TITLE
Kovan

### ISSUE THREAD

**Issue by federicoast** [kleros/gtcr#80]
In this warning sign, we should add some text saying: "To learn how this works, you can use the deployment on the Kovan network".

![FireShot Capture 1038 - Kleros · Curate - https___curate kleros io_factory](https://user-images.githubusercontent.com/16290963/83645074-682aeb80-a588-11ea-9511-8656e4cb00aa.jpg)

**Comment by mtsalenc** [comment]
How about, "To learn how this works, we recommend you deploy on the Kovan network first"?

**Comment by federicoast** [comment]
Sounds good
