### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by federicoast** [kleros/gtcr#82]
It looks as there are two different fonts/font sizes here?

![FireShot Capture 1040 - Kleros · Curate - https___curate kleros io_factory](https://user-images.githubusercontent.com/16290963/83646186-b42a6000-a589-11ea-92ab-d672f542ecb3.jpg)

**Comment by federicoast** [comment]
Not sure, but for some reason, the line of "Acceptance Criteria" and "Click Here..." look a bit different to me.

**Comment by mtsalenc** [comment]
Moved to #72
