### ISSUE TITLE
Error pulling data

### ISSUE THREAD

**Issue by federicoast** [kleros/gtcr#97]
I get these errors.

![FireShot Capture 1049 - Kleros · Curate_ - https___curate kleros io_tcr_0x79](https://user-images.githubusercontent.com/16290963/83782315-0476f000-a666-11ea-96dd-a0f7b872e5fd.jpg)

![FireShot Capture 1050 - Kleros · Curate_ - https___curate kleros io_tcr_0x79](https://user-images.githubusercontent.com/16290963/83782323-08a30d80-a666-11ea-96fd-139415a0baa6.jpg)

**Comment by federicoast** [comment]
I think maybe this happened because my Metamask wallet wasn't connected.

**Comment by mtsalenc** [comment]
Yes, you got rate limited. This should not happen now.
